version: '3'
services:
    api:
        image: 'node:8'
        user: 'node'
        working_dir: /home/node/app
        volumes:
            - ../../apps/api:/home/node/app
        command: 'npm start'
    web-app:
        build:
            dockerfile: Dockerfile 
            context: ../../apps/web-app
        expose:
            - '80'
    proxy:
        restart: always
        build:
            dockerfile: Dockerfile 
            context: ../../apps/nginx
        ports:
            - '3050:80'
